actors_analysis:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"

      # User/password auth
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      role: "{{ env_var('SNOWFLAKE_ROLE', 'ALL_USERS_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'DATAEXPERT_STUDENT') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'COMPUTE_WH') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 1
      client_session_keep_alive: False
      query_tag: "{{ env_var('DBT_SCHEMA') }}"

      # optional connection parameters
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: True # default: True if client_session_keep_alive is False, otherwise None